#!/bin/bash

# check needed vars
if [[ -z $OPENSHIFT_REPO_DIR ]]; then
	echo "Error: OPENSHIFT_REPO_DIR not defined"
	return 1
fi

if [[ -z $OPENSHIFT_DATA_DIR ]]; then
	echo "Error: OPENSHIFT_DATA_DIR not defined"
	return 1
fi

if [[ -z $OPENSHIFT_LOG_DIR ]]; then
	echo "Error: OPENSHIFT_LOG_DIR not defined"
	return 1
fi

# version of play framework to dowload and install
VERSION="1.2.4"
DEPS_PARAMS="--sync"
ID="openshift"
LOG_FILE="${OPENSHIFT_LOG_DIR}play.log"

CONFIG_FILE="${OPENSHIFT_REPO_DIR}.openshift/config"

if [[ -f $CONFIG_FILE ]]; then
	. "$CONFIG_FILE"
fi

# validate version
if [ $VERSION \< "1.2.3" ]; then
	echo "Error: version $VERSION not supported, user version 1.2.3 or higher"
	return 1
fi

PLAY_COMMAND="${OPENSHIFT_DATA_DIR}play-${VERSION}/play"

return 0