#!/bin/bash

# debug
# set -x

#loads VERSION, DEPS_PARAMS, ID, LOG_FILE, PLAY_COMMAND="${OPENSHIFT_DATA_DIR}play-${VERSION}/play"
. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config

if [[ ! $? -eq 0 ]]; then
	exit $?
fi

function lower {
	local result=`echo $1 | tr [:upper:] [:lower:]`
	echo "$result"
}

if [ $(lower $VERSION) = "latest" ]; then

	function latest {

		PLAY_VERSIONS_FILE=${OPENSHIFT_TMP_DIR}/index.html
		curl -o $PLAY_VERSIONS_FILE http://download.playframework.org/releases &> null

		#no pude bajar el archivo con todas las versiones
		if [[ ! -f $PLAY_VERSIONS_FILE ]]; then
			echo "1.2.4"
		else
			echo grep -v '.*-RC.*' index.html | grep -oP 'play-1.*?.zip' | sort -Vru | head -1
			rm $PLAY_VERSIONS_FILE
		fi
	}
	VERSION=$(latest)
	echo "Found latest version of play 1.x: play $VERSION"
fi

PLAY_PATH="play-$VERSION"

# use tmp file just in case it hangs up
PLAY_ARCH="${OPENSHIFT_TMP_DIR}play-$VERSION.zip"

cd "$OPENSHIFT_DATA_DIR"

if [[ -d $PLAY_PATH ]]; then
	echo "Play $VERSION already installed at `pwd`/$PLAY_PATH"
else

	#cleanup, remove other play versions
	for version in [play-]*; do 
		# avoid showing "Removing version [play-]*" message
		if [[ -d $version ]]; then			
			echo "Removing version $version"
			rm -fr $version
		fi
	done

	echo "Installing play $VERSION"

	if [[ -f $PLAY_ARCH ]]; then
		rm $PLAY_ARCH
	fi

	PLAY_URL="http://download.playframework.org/releases/play-$VERSION.zip"
	curl -o $PLAY_ARCH $PLAY_URL

	if [[ ! -f $PLAY_ARCH ]]; then
		echo "Error downloading play $VERSION from $PLAY_URL"
		exit -1
	fi

	unzip "$PLAY_ARCH"
	#rm $PLAY_ARCH

	PLAY_FULL_PATH="${OPENSHIFT_DATA_DIR}${PLAY_PATH}"

	if [[ ! -d $PLAY_FULL_PATH ]]; then
		echo "Error installing play $VERSION to $PLAY_FULL_PATH"
		exit -1
	fi

	# PATH="${PLAY_FULL_PATH}:$PATH"

fi

exit 0